pipelines:
  locality:
    path: /reference/locality
    table: localities
    ingest: N
    clean: Y
    upload: Y

  trends_price:
    path: /markets/trends/price
    table: market_trend_price
    ingest: N
    clean: N
    upload: N

  trends_rent:
    path: /markets/trends/rent
    table: market_trends_rent
    ingest: N
    clean: N
    upload: N

  trends_yield:
    path: /markets/trends/yield
    table: market_trends_yield
    ingest: N
    clean: N
    upload: N

  trends_demand_profile:
    path: /markets/trends/demand-profile
    table: market_trends_demand_profile
    ingest: N
    clean: N
    upload: N

  demand:
    path: /markets/demand
    table: market_demand
    ingest: N
    clean: N
    upload: N

  supply:
    path: /markets/supply
    table: market_supply
    ingest: N
    clean: N
    upload: N

  trends_days_on_market:
    path: /markets/trends/days-on-market
    table: market_supply
    ingest: N
    clean: N
    upload: N